USE test;
CREATE TABLE IF NOT EXISTS server_startup (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, startup_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
INSERT INTO server_startup VALUE ();